# Generated by Django 4.2.6 on 2023-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='costoTotal',
            field=models.IntegerField(),
        ),
    ]
