# Generated by Django 4.2.6 on 2023-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_rename_precio_producto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='ValorPredeterminado', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='ruta_imagen_predeterminada.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto',
            field=models.CharField(default='ValorPredeterminado', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
