# Generated by Django 4.2.6 on 2023-10-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_producto_categoria_producto_imagen_producto_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuModeloDeUsuario',
            fields=[
                ('codigoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('gmail', models.CharField(max_length=45, unique=True)),
                ('contrasena', models.CharField(max_length=45)),
            ],
        ),
    ]
