# Generated by Django 4.2.6 on 2023-10-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0004_tumodelodeusuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TuModeloDeUsuario',
            new_name='db_usuario',
        ),
    ]
