# Generated by Django 4.2.6 on 2023-10-30 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0006_usuario_delete_db_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigoVenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skincare.producto')),
            ],
        ),
    ]
